### ISSUE TITLE
Can't find "explorer" in some invironment

### ISSUE THREAD

**Issue by cser** [Dadido3/batch-rename#2]
Can't run it without adding %SYSTEMROOT% in %PATH% in my home win 10. My work win 10 is works normal O_o.

`Failed to open temporary text file: exec: "explorer": executable file not found in %PATH%
panic: Failed to open temporary text file: exec: "explorer": executable file not found in %PATH%`

**Comment by Dadido3** [comment]
The `%PATH%` environment variable on a fresh and normal windows installation should contain `C:\Windows;C:\Windows\System32;C:\Windows\System32\Wbem;`. For some reason it seems that you are at least missing the `C:\Windows` part.

I have no idea what caused this, but at that point i consider the windows installation broken. The solution, as you have already figured out, is to fix the `%PATH%` environment variable by adding the missing entries. The order may be somewhat important, and these entries should be at the top of the list.

**Comment by cser** [comment]
Maybe the right solution is not to force users to add variables, but to embed an availability check explorer.exe and search in the specified folders in the application itself?

**Comment by cser** [comment]
How to test it? - Just run inside console with custom %PATH% variable

**Comment by Dadido3** [comment]
I'll probably rely on the "Open file with default application" implementation from [github.com/skratchdot/open-golang](https://github.com/skratchdot/open-golang) in the future. This should solve your problem and has the neat side effect that it also works on Linux and macOS.

**Comment by Dadido3** [comment]
f51715eedb16419324e51fc5f0f802c05791f744 should fix this. If you got some time to test it, tell me if it works.

**Comment by cser** [comment]
Thanks!
Yes, it works now (I clear %path%, check old version, check new version - new version works without showing this error)
